### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by patrickleet** [crossplane-contrib/provider-okta#2]
Hi, just curious - this seems to be missing a lot of resources that are available in the terraform package for okta - samlapps, etc. 

Are there plans to add those?

What would that process even look like? Haven't used upjet at all.

**Comment by rjop-hccgt** [comment]
hi @patrickleet the latest release has been created which includes several missing okta types [Marketplace](https://marketplace.upbound.io/providers/crossplane-contrib/provider-okta/v0.2.0). If you feel there are other types that might be needed let me know
